// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// MockCovidService is a mock of CovidService interface.
type MockCovidService struct {
	ctrl     *gomock.Controller
	recorder *MockCovidServiceMockRecorder
}

// MockCovidServiceMockRecorder is the mock recorder for MockCovidService.
type MockCovidServiceMockRecorder struct {
	mock *MockCovidService
}

// NewMockCovidService creates a new mock instance.
func NewMockCovidService(ctrl *gomock.Controller) *MockCovidService {
	mock := &MockCovidService{ctrl: ctrl}
	mock.recorder = &MockCovidServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCovidService) EXPECT() *MockCovidServiceMockRecorder {
	return m.recorder
}
