version: "3.5"
services:
  covid_redis:
    image: bitnami/redis:latest
    container_name: covid_redis
    environment:
      REDIS_PASSWORD: redispassword1234
    restart: always

  covid_api:
    container_name: covid_api
    image: tourwat-api:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_PORT: "9090"
      APP_PREFIX: "/api"

      REDIS_HOST: "covid_redis"
      REDIS_PASSWORD: "redispassword1234"
      REDIS_DB: "0"
      REDIS_PORT: "6379"

    ports:
      - "9090:9090"
    depends_on:
      - covid_redis
    restart: always

volumes:
  covid_api_volume:
